### ISSUE TITLE
Compatibilitty with Inspecio

### ISSUE THREAD

**Issue by SplendidAlakey** [AViewFromTheTop/LunaSlimes#1]
**MC** 1.19.2
**QFAPI** 4.0.0-beta.25
**Luna Slimes** 1.4
**[Inspecio](https://www.curseforge.com/minecraft/mc-mods/inspecio)** 1.6.0

When Luna Slimes is installed, Inspecio fails to render a slime, when viewing its spawn egg. I assume, it happens because Luna Slimes modifies the spawning animation. Not sure, if this is something you can address on your side, so let me know, if this needs to be reported to Inspecio, instead.

With Luna Slimes

![2022-12-30_05 20 04](https://user-images.githubusercontent.com/86702831/210034404-0ff78eef-ea4c-401b-9768-b10f0ff87d65.png)

Without Luna Slimes

![2022-12-30_05 22 41](https://user-images.githubusercontent.com/86702831/210034408-9877df90-933f-41d6-99c9-6cd2a8aa3f25.png)

**Comment by AViewFromTheTop** [comment]
Fixed in 1.5!
