### ISSUE TITLE
Slimes and magma cubes are invisible in Better Statistics Screen

### ISSUE THREAD

**Issue by SplendidAlakey** [AViewFromTheTop/LunaSlimes#4]
**MC** 1.19.2
**[Better Statistics Screen](https://www.curseforge.com/minecraft/mc-mods/better-stats)** 2.7.1
**Luna Slimes** 1.6

Seems to be similar to #1. Edit: actually, just realized that it's also broken in Inspecio again.

With Luna Slimes:
![1](https://github.com/AViewFromTheTop/LunaSlimes/assets/86702831/26e61381-27ae-4f69-8716-ce08820cc4da)

Without Luna Slimes:
![2](https://github.com/AViewFromTheTop/LunaSlimes/assets/86702831/368c3c40-94fb-435c-bed3-2eacc9c26423)

**Comment by AViewFromTheTop** [comment]
Dang.

**Comment by AViewFromTheTop** [comment]
Fixed in 1.7!
