### ISSUE TITLE
incompatibility with Supplementaries' jar and mob cage

### ISSUE THREAD

**Issue by peow** [AViewFromTheTop/LunaSlimes#5]
the Supplementaries mod has 2 items that allow you to capture small creatures, the Jars and the Mob Cages, both look like this when you capture a small Slime or a small Magma Cube

![2023-11-11_11 44 00](https://github.com/AViewFromTheTop/LunaSlimes/assets/105888751/2e97650e-8cd6-4604-afa3-403ae1026143)

however, when Luna Slimes is activated (which changes the texture of the Slime and Magma Cube) the mobs become invisible

![2023-11-11_11 46 32](https://github.com/AViewFromTheTop/LunaSlimes/assets/105888751/00468aad-e241-423a-8663-c09d7484176f)

im playing in fabric 1.20.1, Supplementaries v1.20-2.6.20, Lunaslimes v1.6.1-1.20

to reproduce the bug put this inside an command block, it will summon a jar with an small Slime inside:

/setblock ~1 ~ ~ supplementaries:jar[facing=south]{MobHolder:{EntityData:{AbsorptionAmount:0.0f,Air:300s,Attributes:[{Base:0.30000001192092896d},{Base:16.0d,Modifiers:[{Amount:-0.06687010849664278d,Operation:1,UUID:[I;-2137834730,-378846371,-1110228829,-1541614037]}],Name:"minecraft:generic.follow_range"},{Base:1.0d,Name:"minecraft:generic.max_health"}],Motion:[0.0d,-0.0784000015258789d,0.0d],OnGround:1b,PersistenceRequired:1b,Pos:[0.5d,0.0626d,0.5d],Rotation:[0.0f,0.0f],Size:0,id:"minecraft:slime",wasOnGround:1b},Name:"Slime",Scale:0.72087663f,UUID:[I;1745007123,798966524,-1792024447,301302059]}}

if you are going to fix this problem, please make an update to 1.20.1, i would really like to be able to trap slimes and leave them as decoration

**Comment by AViewFromTheTop** [comment]
I fixed a similar issue on Wilder Wild a while ago.
I promise I’ll get back to this mod soon.

**Comment by peow** [comment]
ok

**Comment by AViewFromTheTop** [comment]
Fixed in 1.7!

**Comment by peow** [comment]
thanks, It's sad that you need Fabric Loader 0.15 but thanks
